#!/bin/bash
# Basic backports.list. Used to install kernel from backports

if $use_backports_kernel; then
echo 'using backports'
for backports_mirror in $backports_mirrors; do
cat >> $imagedir/etc/apt/sources.list.d/backports.list <<EOF
deb     $backports_mirror wheezy-backports         main contrib non-free
deb-src $backports_mirror wheezy-backports         main contrib non-free
EOF
done
fi
