#!/bin/bash
# Basic sources.list. The current packages work on all supported versions of
# Debian, so at least for now we're using a distribution name independent of
# those.
cat > $imagedir/etc/apt/sources.list.d/goog.list <<EOF
deb     http://goog-repo.appspot.com/debian pigeon main
EOF
