#!/bin/bash
# Prefer backports kernel

if $use_backports_kernel; then
echo 'using backports'
cat >> $imagedir/etc/apt/preferences.d/backports-kernel.pref <<EOF
Package: linux-image-* initramfs-tools
Pin: release n=wheezy-backports
Pin-Priority: 500
EOF
fi
