#!/bin/bash
# Add some basic packages we are going to need
packages+=('udev')
packages+=('openssh-server')
# We could bootstrap without locales, but things just suck without them,
# error messages etc.
packages+=('locales')
# Needed for the init scripts
packages+=('file')

# We will need to format the volume, so we need xfsprogs
[ $filesystem = 'xfs' ] && host_packages+=('xfsprogs')
# In order to make sure a volume is not busy, before unmounting we need lsof
host_packages+=('lsof')
host_packages+=('debootstrap')

#BM Specific packages
packages+=('mosh')
packages+=('vim')
packages+=('vim-scripts')
packages+=('screen')
packages+=('git')
packages+=('htop')
packages+=('python')
packages+=('etckeeper')
packages+=('rcconf')
packages+=('htop')
packages+=('emacs')
packages+=('build-essential')
packages+=('exim4-daemon-light')
packages+=('mailutils')
packages+=('dnsutils')
packages+=('fail2ban')
packages+=('ufw')
packages+=('sudo')
packages+=('rsync')
packages+=('less')
packages+=('libssl-dev')
packages+=('zlib1g-dev')
packages+=('e2fslibs-dev')
packages+=('ca-certificates')
